name: 'Add text to body of pr'
description: 'Adds a message to body of pr'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  msg:
    description: 'Message to add'
    required: true
  title-regex:
    description: 'Regex to compare pr title with'
    required: false
    default: ''
jobs:
  add-message-to-description:
    run:
      using: 'node12'
      main: 'messageToDescription.js'
  compare-title-with-regex:
    if: title-regex != ''
    run:
      using: 'node12'
      main: 'compareRegex.js'
